const fs = require('fs');
const path = require('path');

const key = process.env.WEB3FORMS_KEY || '';

const content = `// Auto-generated by scripts/build-env.js — do not edit manually
window.__ENV = {
  WEB3FORMS_KEY: '${key}',
};
`;

const out = path.join(__dirname, '..', 'src', 'js', 'env.js');
fs.writeFileSync(out, content, 'utf-8');
console.log(`✅ env.js gerado com WEB3FORMS_KEY=${key ? '****' + key.slice(-4) : '(vazio)'}`);
